parameters:
    ezpublish.core.io.tolerant_service.class: Ez\Summer\CampBundle\Override\ToleranterIOService
    ezpublish.search.solr.query.content.criterion_visitor.map_location_distance_range.class: Ez\Summer\CampBundle\Override\MapLocationDistanceRange

    ezpublish.fieldType.ezurl.class: Ez\Summer\CampBundle\API\Repository\Tests\FieldType\SearchableUrl

    ezpublish.fieldType.indexable.ezurl.class: Ez\Summer\CampBundle\Core\FieldType\Url\SearchField

services:
    ezpublish.fieldType.indexable.ezurl:
        class: %ezpublish.fieldType.indexable.ezurl.class%
        tags:
            - {name: ezpublish.fieldType.indexable, alias: ezurl}
