parameters:
    ezpublish.core.io.tolerant_service.class: Ez\Summer\CampBundle\Override\ToleranterIOService
    ezpublish.search.solr.query.content.criterion_visitor.map_location_distance_range.class: eZ\Summer\CampBundle\Override\MapLocationDistanceRange

    ezpublish.fieldType.ezurl.class: Ez\Summer\CampBundle\API\Repository\Tests\FieldType\SearchableUrl

services:
#    ez_summer_camp.example:
#        class: Ez\Summer\CampBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
